"""
learning.py — FeedbackAnalyzer

Learns from every agent correction (original AI draft vs approved final).
Stores classified lessons in a local SQLite database and injects relevant
lessons into future system prompts so the AI improves over time.

Public API
----------
  analyzer = get_analyzer()              # module-level singleton
  analyzer.analyze_correction(orig, final, ctx)  -> dict | None
  analyzer.get_lessons(emotion, intent, topic, customer_name) -> list[str]
  analyzer.get_report(days=30)           -> dict
"""

import json
import os
import sqlite3
import sys
from collections import Counter
from datetime import datetime, timedelta

_DIR = os.path.dirname(os.path.abspath(__file__))
if _DIR not in sys.path:
    sys.path.insert(0, _DIR)

from paths import resolve_data_file

# Lazy-loaded so we don't force main.py to import at module level in edge cases
_client  = None
_CONFIG  = None
_COMPANY = "Unknown"


def _load_ai():
    global _client, _CONFIG, _COMPANY
    if _client is None:
        try:
            from main import client, CONFIG   # noqa: PLC0415
            _client  = client
            _CONFIG  = CONFIG
            _COMPANY = CONFIG["company"]["name"]
        except Exception:
            pass
    return _client, _CONFIG


# ==============================================================================
# AI PROMPT
# ==============================================================================

_CLASSIFY_SYSTEM = """\
You are a QA analyst comparing two B2B customer-service email drafts.
The "ORIGINAL" was generated by an AI agent.
The "FINAL" was approved by a human agent after editing.

Classify the nature and significance of the edit.

Return ONLY valid JSON (no extra text):
{
  "correction_type": "tone" | "factual" | "added_info" | "removed_info" | "policy" | "minor",
  "severity":        "critical" | "significant" | "minor",
  "lesson":          "one-sentence rule the AI must follow in this situation next time",
  "example_before":  "first 100 chars of the changed section from the ORIGINAL",
  "example_after":   "first 100 chars of the corrected section from the FINAL"
}

correction_type definitions:
- tone        : empathy level, emotional register, or formality was wrong
- factual     : incorrect data (date, order number, name, amount) was fixed
- added_info  : important information was missing and was added
- removed_info: incorrect or inappropriate content was removed
- policy      : response violated a company policy or procedure
- minor       : small phrasing / style improvement, no substantive change
"""


# ==============================================================================
# FEEDBACKANALYZER
# ==============================================================================

class FeedbackAnalyzer:

    def __init__(self):
        self._db_path = resolve_data_file("lessons.db")
        self._ensure_table()

    # ── DB setup ──────────────────────────────────────────────────────────────

    def _ensure_table(self) -> None:
        with sqlite3.connect(self._db_path) as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS lessons (
                    id              INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp       TEXT    NOT NULL,
                    company         TEXT,
                    customer_name   TEXT,
                    emotion         TEXT,
                    intensity       TEXT,
                    intent          TEXT,
                    topic           TEXT,
                    correction_type TEXT,
                    severity        TEXT,
                    lesson          TEXT,
                    example_before  TEXT,
                    example_after   TEXT,
                    times_applied   INTEGER DEFAULT 0,
                    times_effective INTEGER DEFAULT 0
                )
            """)
            # Migrate existing DBs that predate these columns
            existing = {
                row[1]
                for row in conn.execute("PRAGMA table_info(lessons)").fetchall()
            }
            for col, typedef in (
                ("times_applied",   "INTEGER DEFAULT 0"),
                ("times_effective", "INTEGER DEFAULT 0"),
            ):
                if col not in existing:
                    conn.execute(f"ALTER TABLE lessons ADD COLUMN {col} {typedef}")
            conn.commit()

    # ── Core methods ──────────────────────────────────────────────────────────

    def analyze_correction(
        self, original: str, final: str, context: dict
    ) -> dict | None:
        """
        Compare original AI draft vs agent-approved final.

        If unchanged → returns None (nothing to learn).
        Otherwise makes an AI call to classify the correction, stores the
        lesson in SQLite, and returns the classified dict.

        This method is safe to call from a background thread.
        """
        if not original or not final:
            return None
        if original.strip() == final.strip():
            return None

        ai_client, cfg = _load_ai()
        if ai_client is None:
            return None

        try:
            user_msg = (
                f"ORIGINAL (AI-generated):\n{original}\n\n"
                f"FINAL (agent-approved):\n{final}\n\n"
                f"Context — emotion: {context.get('emotion', '?')}, "
                f"intensity: {context.get('intensity', '?')}, "
                f"intent: {context.get('intent', '?')}, "
                f"topic: {context.get('topic', '?')}"
            )

            ai_cfg = (cfg or {}).get("ai", {})
            models = ai_cfg.get("models", {})
            model  = (
                models.get("simple", {}).get("model")
                or ai_cfg.get("model", "gpt-4.1-mini")
            )

            response = ai_client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": _CLASSIFY_SYSTEM},
                    {"role": "user",   "content": user_msg},
                ],
                max_tokens=300,
                temperature=0.1,
                response_format={"type": "json_object"},
            )
            result = json.loads(response.choices[0].message.content)

        except Exception:
            return None

        # Persist lesson
        try:
            with sqlite3.connect(self._db_path) as conn:
                conn.execute(
                    "INSERT INTO lessons "
                    "(timestamp, company, customer_name, emotion, intensity, intent, topic, "
                    " correction_type, severity, lesson, example_before, example_after) "
                    "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
                    (
                        datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                        context.get("company", _COMPANY),
                        context.get("customer_name", ""),
                        context.get("emotion", ""),
                        context.get("intensity", ""),
                        context.get("intent", ""),
                        context.get("topic", ""),
                        result.get("correction_type", "minor"),
                        result.get("severity", "minor"),
                        result.get("lesson", "")[:500],
                        result.get("example_before", "")[:200],
                        result.get("example_after", "")[:200],
                    ),
                )
                conn.commit()
        except Exception:
            pass

        return result

    def get_lessons(
        self,
        emotion: str | None       = None,
        intent:  str | None       = None,
        topic:   str | None       = None,
        customer_name: str | None = None,
        limit: int                = 3,
    ) -> list[dict]:
        """
        Return up to `limit` unique lessons, scored by relevance.
        Each entry: {"id": int, "lesson": str}

          +8 — same customer_name
          +4 — same intent
          +2 — same emotion
          +1 — same topic
        Within each score tier: most recent first.
        Returns empty list if DB is empty or unavailable.
        """
        try:
            with sqlite3.connect(self._db_path) as conn:
                conn.row_factory = sqlite3.Row
                rows = conn.execute(
                    "SELECT id, lesson, customer_name, emotion, intent, topic, timestamp "
                    "FROM lessons WHERE lesson != '' "
                    "ORDER BY timestamp DESC LIMIT 500"
                ).fetchall()
        except Exception:
            return []

        def _score(row) -> int:
            s = 0
            if customer_name and row["customer_name"] == customer_name:
                s += 8
            if intent and row["intent"] == intent:
                s += 4
            if emotion and row["emotion"] == emotion:
                s += 2
            if topic and row["topic"] == topic:
                s += 1
            return s

        scored = [(row, _score(row)) for row in rows]
        scored = [(r, s) for r, s in scored if s > 0]
        scored.sort(key=lambda x: -x[1])

        seen:   set[str]       = set()
        result: list[dict]     = []
        for row, _ in scored:
            lesson = row["lesson"]
            if lesson and lesson not in seen:
                seen.add(lesson)
                result.append({"id": row["id"], "lesson": lesson})
                if len(result) >= limit:
                    break
        return result

    def mark_applied(self, lesson_ids: list) -> None:
        """Increment times_applied for each lesson ID (draft was seen but modified/rejected)."""
        if not lesson_ids:
            return
        try:
            with sqlite3.connect(self._db_path) as conn:
                conn.executemany(
                    "UPDATE lessons SET times_applied = times_applied + 1 WHERE id = ?",
                    [(lid,) for lid in lesson_ids],
                )
                conn.commit()
        except Exception:
            pass

    def mark_effective(self, lesson_ids: list) -> None:
        """Increment both times_applied and times_effective (draft approved unchanged)."""
        if not lesson_ids:
            return
        try:
            with sqlite3.connect(self._db_path) as conn:
                conn.executemany(
                    "UPDATE lessons SET "
                    "times_applied = times_applied + 1, "
                    "times_effective = times_effective + 1 "
                    "WHERE id = ?",
                    [(lid,) for lid in lesson_ids],
                )
                conn.commit()
        except Exception:
            pass

    def get_report(self, days: int = 30) -> dict:
        """
        Returns performance report over the last `days` days:
          total_interactions  — from logs.json
          total_corrections   — corrections stored in lessons.db
          correction_rate     — % of interactions that triggered a correction
          most_common_type    — most frequent correction_type
          intent_corrections  — top-5 intents by correction count {intent: count}
          trend               — "improving" | "stable" | "worsening"
          daily_data          — list[{date, corrections, interactions}] for charting
          period_days         — echoed back for display
        """
        cutoff = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")
        cutoff_ts = cutoff + " 00:00:00"

        # ── Corrections from SQLite ───────────────────────────────────────
        try:
            with sqlite3.connect(self._db_path) as conn:
                conn.row_factory = sqlite3.Row
                lessons = conn.execute(
                    "SELECT * FROM lessons WHERE timestamp >= ? ORDER BY timestamp ASC",
                    (cutoff_ts,)
                ).fetchall()
        except Exception:
            lessons = []

        total_corrections = len(lessons)

        # Daily correction counts
        daily_corr: dict[str, int] = {}
        for r in lessons:
            day = r["timestamp"][:10]
            daily_corr[day] = daily_corr.get(day, 0) + 1

        # ── Interactions from logs.json ───────────────────────────────────
        total_interactions = 0
        daily_inter: dict[str, int] = {}
        try:
            logs_path = resolve_data_file("logs.json")
            if os.path.exists(logs_path):
                with open(logs_path, "r", encoding="utf-8") as f:
                    all_logs = json.load(f)
                for entry in all_logs:
                    if (
                        entry.get("log_type") != "erp_action"
                        and entry.get("customer_msg")
                        and entry.get("timestamp", "") >= cutoff
                    ):
                        total_interactions += 1
                        day = entry["timestamp"][:10]
                        daily_inter[day] = daily_inter.get(day, 0) + 1
        except Exception:
            pass

        correction_rate = (
            round(total_corrections / total_interactions * 100, 1)
            if total_interactions > 0 else 0.0
        )

        # ── Daily merged data ─────────────────────────────────────────────
        all_days = sorted(set(list(daily_corr) + list(daily_inter)))
        daily_data = [
            {
                "date":         d,
                "corrections":  daily_corr.get(d, 0),
                "interactions": daily_inter.get(d, 0),
            }
            for d in all_days
        ]

        # ── Correction-type distribution ──────────────────────────────────
        types = [r["correction_type"] for r in lessons if r["correction_type"]]
        type_counter = Counter(types)
        most_common_type = type_counter.most_common(1)[0][0] if types else None

        # ── Intent correction counts ──────────────────────────────────────
        intents = [r["intent"] for r in lessons if r["intent"]]
        intent_corrections = dict(Counter(intents).most_common(5))

        # ── Trend: compare severity averages of first vs second half ──────
        def _sev(r) -> int:
            return {"critical": 2, "significant": 1, "minor": 0}.get(r["severity"], 0)

        mid   = len(lessons) // 2
        first = lessons[:mid]
        second= lessons[mid:]
        first_avg  = sum(_sev(r) for r in first)  / len(first)  if first  else 0
        second_avg = sum(_sev(r) for r in second) / len(second) if second else 0
        diff  = second_avg - first_avg
        trend = "improving" if diff < -0.1 else "worsening" if diff > 0.1 else "stable"

        return {
            "total_interactions": total_interactions,
            "total_corrections":  total_corrections,
            "correction_rate":    correction_rate,
            "most_common_type":   most_common_type,
            "intent_corrections": intent_corrections,
            "trend":              trend,
            "daily_data":         daily_data,
            "period_days":        days,
            "type_counts":        dict(type_counter),
        }


# ==============================================================================
# MODULE-LEVEL SINGLETON
# ==============================================================================

_instance: FeedbackAnalyzer | None = None


def get_analyzer() -> FeedbackAnalyzer:
    global _instance
    if _instance is None:
        _instance = FeedbackAnalyzer()
    return _instance
